{
  "swagger": "2.0",
  "info": {
    "title": "",
    "version": ""
  },
  "paths": {
    "/table": {
      "get": {
        "summary": "",
        "description": "",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/TableData"
            },
            "examples": {
              "application/json": [
                ["Column 1", "Column 2", "Column 3"],
                ["Row 1, Col 1", "Row 1, Col 2", "Row 1, Col 3"],
                ["Row 2, Col 1", "Row 2, Col 2", "Row 2, Col 3"]
              ]
            }
          }
        }
      }
    }
  },
  "definitions": {
    "TableData": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  }
}
